// app/api/planner/schedule/route.ts
// CRUD for marketing_schedule
// GET — list schedule items (filterable by date range, property, status)
// POST — create a new scheduled item
// PATCH — update status, caption, date
// DELETE — remove a schedule item

import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function GET(req: Request) {
  try {
    const supabase = await createClient();
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const url = new URL(req.url);
    const startDate = url.searchParams.get("start");
    const endDate = url.searchParams.get("end");
    const propertyId = url.searchParams.get("propertyId");
    const status = url.searchParams.get("status");

    let query = supabase
      .from("marketing_schedule")
      .select("*")
      .eq("user_id", session.user.id)
      .order("scheduled_date", { ascending: true });

    if (startDate) query = query.gte("scheduled_date", startDate);
    if (endDate) query = query.lte("scheduled_date", endDate);
    if (propertyId) query = query.eq("property_id", propertyId);
    if (status) query = query.eq("status", status);

    const { data, error } = await query;
    if (error) throw error;

    return NextResponse.json({ items: data || [] });
  } catch (error) {
    console.error("Schedule GET error:", error);
    return NextResponse.json({ error: "Failed to load schedule" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const supabase = await createClient();
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await req.json();
    const { propertyId, planId, scheduledDate, platform, contentType, caption, assetUrl, autoGenerated } = body;

    if (!scheduledDate || !platform || !contentType) {
      return NextResponse.json({ error: "Missing required fields: scheduledDate, platform, contentType" }, { status: 400 });
    }

    const { data, error } = await supabase
      .from("marketing_schedule")
      .insert({
        user_id: session.user.id,
        property_id: propertyId || null,
        plan_id: planId || null,
        scheduled_date: scheduledDate,
        platform,
        content_type: contentType,
        caption: caption || null,
        asset_url: assetUrl || null,
        auto_generated: autoGenerated || false,
        status: "pending",
      })
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ item: data });
  } catch (error) {
    console.error("Schedule POST error:", error);
    return NextResponse.json({ error: "Failed to create schedule item" }, { status: 500 });
  }
}

export async function PATCH(req: Request) {
  try {
    const supabase = await createClient();
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const body = await req.json();
    const { id, status, caption, scheduledDate } = body;

    if (!id) {
      return NextResponse.json({ error: "Missing id" }, { status: 400 });
    }

    const updates: Record<string, unknown> = {};
    if (status) updates.status = status;
    if (caption !== undefined) updates.caption = caption;
    if (scheduledDate) updates.scheduled_date = scheduledDate;

    const { data, error } = await supabase
      .from("marketing_schedule")
      .update(updates)
      .eq("id", id)
      .eq("user_id", session.user.id)
      .select()
      .single();

    if (error) throw error;

    // If marking as posted, also record the marketing action
    if (status === "posted" && data) {
      await supabase.from("marketing_actions").insert({
        user_id: session.user.id,
        property_id: data.property_id,
        action_type: "planner_item_completed",
        platform: data.platform,
        content_type: data.content_type,
        metadata: { schedule_id: id },
      });
    }

    if (status === "skipped" && data) {
      await supabase.from("marketing_actions").insert({
        user_id: session.user.id,
        property_id: data.property_id,
        action_type: "planner_item_skipped",
        platform: data.platform,
        content_type: data.content_type,
        metadata: { schedule_id: id },
      });
    }

    return NextResponse.json({ item: data });
  } catch (error) {
    console.error("Schedule PATCH error:", error);
    return NextResponse.json({ error: "Failed to update schedule item" }, { status: 500 });
  }
}

export async function DELETE(req: Request) {
  try {
    const supabase = await createClient();
    const { data: { session } } = await supabase.auth.getSession();
    if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const url = new URL(req.url);
    const id = url.searchParams.get("id");

    if (!id) {
      return NextResponse.json({ error: "Missing id" }, { status: 400 });
    }

    const { error } = await supabase
      .from("marketing_schedule")
      .delete()
      .eq("id", id)
      .eq("user_id", session.user.id);

    if (error) throw error;

    return NextResponse.json({ deleted: true });
  } catch (error) {
    console.error("Schedule DELETE error:", error);
    return NextResponse.json({ error: "Failed to delete schedule item" }, { status: 500 });
  }
}
